### ISSUE TITLE
i cant see my photos from my album

### ISSUE THREAD

**Issue by lee-jun-fan** [hermanho/MMM-GooglePhotos#1]
i have followed all steps what you have mentioned in read me document. but photos not display in magic mirror. please give some suggestion for me...

Failed to load resource: the server responded with a status of 404 (Not Found) 
:8080/modules/MMM-GooglePhotos//MMM-GooglePhotos.js

**Comment by eouia** [comment]
Where have you found this error? More details I need for researching.

**Comment by eouia** [comment]
Good to you. I'll close this issue.
