### ISSUE TITLE
Image Fullscreen 

### ISSUE THREAD

**Issue by paddyhughes** [hermanho/MMM-GooglePhotos#10]
Hi eouia

Thanks for the great Photo module.

The Module works but once i change the  showWidth & showHeight from px to % for fullscreen 
the MagicMirror config screen displays.
`
		{
  module: "MMM-GooglePhotos",
  position: "top_right",
  config: {
    albumId: "MY Code ******************", // your album id from result of `auth_and_test.js`
    refreshInterval: 1000*60,
    scanInterval: 1000*60*10, // too many scans might cause API quota limit also.
    //note(2018-07-29). It is some weird. API documents said temporal image url would live for 1 hour, but it might be broken shorter. So, per 10 min scanning could prevent dead url.

    sort: "time", //'time', 'reverse', 'random'
    showWidth: "100%", // how large the photo will be shown as. (e.g;'100%' for fullscreen)
    showHeight: "100%",
    originalWidthPx: 800, // original size of loaded image. (related with image quality)
    originalHeightPx: 600, // Bigger size gives you better quality, but can give you network burden.
    mode: "cover", // "cover" or "contain" (https://www.w3schools.com/cssref/css3_pr_background-size.asp)
  }
},
`

**Comment by eouia** [comment]
Nice to you. I'll close this issue.
