### ISSUE TITLE
Error 403: access_denied

### ISSUE THREAD

**Issue by robertybob** [hermanho/MMM-GooglePhotos#109]
Hi. I'm trying to generate the token. When I go to generate the token, no window opens so I have to copy and paste the URL. When I go this, I'm greeted by the following

![image](https://user-images.githubusercontent.com/2610395/120936812-c3df0600-c701-11eb-83ab-bd4de4c4faf2.png)

I've followed all of the steps in the readme, so I'm confused why I'm presented with this.

**Comment by aneaville** [comment]
This appears to be an issue with your google project, not so much this app.
Have you checked your google project to make sure you have a client ID?
![image](https://user-images.githubusercontent.com/13342606/121021734-4c43c200-c767-11eb-971e-bfbbfb78ca73.png)

There have been similar errors in other issues. You can search through closed issues to see if anything suggested in those can help you.

**Comment by robertybob** [comment]
I've solved this now. I had to add my same email address as a member to my project, under the permissions section

![image](https://user-images.githubusercontent.com/2610395/121747207-f2dce980-cafe-11eb-8e2e-2cc06146930c.png)

May be worth adding this to the readme as a possible step that users will have to do once they've created their project :)
