### ISSUE TITLE
error after pasting auth code

### ISSUE THREAD

**Issue by ShakirAkbari** [hermanho/MMM-GooglePhotos#11]
I get the below error after I paste my authorisation code  -- can you help me make sense of what I'm doing wrong

Paste your code: 4/ABC123.....
(node:7293) UnhandledPromiseRejectionWarning: Error: Error getting tokens:
    at oauthClient.getToken (/home/pi/MagicMirror/MMM-GooglePhotos/auth.js:93:24)
    at /home/pi/MagicMirror/MMM-GooglePhotos/node_modules/google-auth-library/build/src/auth/oauth2client.js:158:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:7293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eouia** [comment]
Weird error. I doubt it might be cause by these two possible reasons.
- Pasted code is wrong: missed some characters in the end or, added unnecessary additional chars.
- You might have several projects and have confusing project id.

But Not sure.

**Comment by ShakirAkbari** [comment]
I think it might be an issue with more than one project - I'll start over with just one project

thank you for responding - I'll try again today and let you know

**Comment by ShakirAkbari** [comment]
its almost definitely an issue with enabling the API for the wrong project. 

Thanks again for helping. I'll try to confirm tonight and will close this issue afterwards

**Comment by ShakirAkbari** [comment]
still cant get it going - i'm definitely on the right project now (i re-created with a new name which auth_and_test.js points to) - i dont think it is an issue with pasting the wrong code or adding characters - its just a copy and paste and i do confirm the string matches before pressing enter in shell. is there anything i can send you to help with troubleshooting?

**Comment by eouia** [comment]
Check your credentials.json. Did you make new credentials.json from new project? credentials.json and  authCode should be from same project.

**Comment by ShakirAkbari** [comment]
Yes, I did that a few times. I'll try again today and write down everystep
of what I am doing

**Comment by eouia** [comment]
Sorry. But that error itself is not coming from program. It says just your token or credential is not valid. That is not my program's fault.
- Check whether Photos Library API is enabled.
- Check whether credentials are made as "Other" type of "OAuth Client Id"
- Check whether OAuth Consent Screen is created and saved (No need to verify)

Those are all I can suggest. I wish you have a good luck.

**Comment by ShakirAkbari** [comment]
thanks again. i havent gotten it working yet but am confident that i'm following the prescribed steps. the photo api is enabled, the credentials are for "other" and "oauth client id". consent screen is created. i opened the credentials.json and the client secret matches the right project. and i confirm the code after pasting. 

my next steps are that I'll create a new google account and try again from with that.

i really appreciate your help here, and i am sure it the issue is something i am doing wrong. please feel free to close this issue if you'd like. i can message you separately if that is ok with you.

**Comment by eouia** [comment]
Good to you. Have a nice day.

**Comment by atiris** [comment]
I had the same problem today and I proceeded as follows: Deleted node_modules and token.json and generated a new key in credentials.json. After re-installation (only `npm install`, so without electron-rebuild), everything was ok. I do not know what a problem, since I did everything at the same time, maybe it helped I deleted the token.json file.

**Comment by lbyerley** [comment]
Hi Eouia,

I am having the same problem. I cannot generate a token.js file. I've pasted the error below that I get when using node generate_token.js. It opens the google approval page and I get the key but when I paste it under code I get this error. Have tried all solutions listed on Github.

(node:23445) UnhandledPromiseRejectionWarning: TypeError: invalid options argument
    at optsArg (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/mkdirp/index.js:11:10)
    at /home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:49:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23445) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
