### ISSUE TITLE
How do I get the images to be centered?

### ISSUE THREAD

**Issue by bcoleg** [hermanho/MMM-GooglePhotos#14]
The image is slightly offset to the left.  I have the position set to lower_third.  How do I center the images?

**Comment by eouia** [comment]
Describe the rules for CSS selector `#GPHOTO` in your `css/custom.css` to adjust padding or margin as your wants.
Unbalance of left and right margin might come from original CSS rules of MM itself. I'm not sure how your environments are set, but my module would be aligned by rules of CSS. So you have to find why `lower_third` has unbalanced margin and correct it, Or modify `#GPHOTO` to adjust the margin in that area for better showing.

**Comment by eouia** [comment]
Have you solved this issue? I'll close this because there is no more feedback. Anyway I wish a good luck for you.
