### ISSUE TITLE
Rediscover This Day

### ISSUE THREAD

**Issue by mganoe** [hermanho/MMM-GooglePhotos#15]
Is it possible to access Google's auto generated Rediscover this Day albums, or possibly apply a date filter to the request?

**Comment by eouia** [comment]
Those albums(?) cannot be reached by Googles SDK API. 
And unfortunately, Album and filter(including date, category, ...) cannot be working together. Sorry. (I didn't implement filter, because I'd think it's better to organize photos by manual as wallpapers)
