### ISSUE TITLE
Receiving Google Token does not work

### ISSUE THREAD

**Issue by keremsevimli** [hermanho/MMM-GooglePhotos#16]
Hi,
when I start auth and test the browser starts and I can sign in or choose an account. But when I choose an account the page refreshes and gets to the same page (choose account). It does not matter which account I choose. It is always the same.

Is there something wrong in calling the google api? Any other ideas?
Best regards,
KSE

**Comment by eouia** [comment]
Copy the URL and try it another browser. It would be cookie problem.

**Comment by keremsevimli** [comment]
yes that was the issue
