### ISSUE TITLE
Request: Show Album-Name or Location or other attributes from Photo

### ISSUE THREAD

**Issue by keremsevimli** [hermanho/MMM-GooglePhotos#18]
It would be nice if it is possible to show the albumname or other attributes provided by a photo? Also it would be nice if the position can be defined where to "print".

**Comment by eouia** [comment]
Nice suggestion. Those features are implemented in my MMM-DropboxWallpaper, but unfortunately, GooglePhotos API will return only these informations. So your request couldn't be done. It doesn't return any geo information or any other interesting things.


```
{ 
  id: 'AJQR...',
  productUrl:'https://photos.google.com/lr/album/AJQR...',
  baseUrl:'https://lh3.googleusercontent.com/lr/AGWb...',
  mimeType: 'image/heif',
  mediaMetadata: { 
    creationTime: '2018-07-14T12:11:47Z',
    width: '4032',
    height: '3024',
    photo: { 
      cameraMake: 'Apple',
      cameraModel: 'iPhone X',
      focalLength: 6,
      apertureFNumber: 2.4,
      isoEquivalent: 16 
    } 
  },
  filename: 'IMG_0569...' 
}
```
