### ISSUE TITLE
There is no scanned photo currently.

### ISSUE THREAD

**Issue by Season000** [hermanho/MMM-GooglePhotos#19]
Everything's OK but it doesn't show pictures.Magicmirror display is normal.No pictures displayed
The terminal displays the following prompts

`[GPHOTO] Scan finished : 0`
`There is no scanned photo currently.`
I created several new atlases and added pictures, but none of them responded.
Is it wrong for me to create an atlas in Google Album?

**Comment by eouia** [comment]
What is your image type and file extentions? .jpg? .png?
And Sorry for my poor english. I cannot understand what `atlas` means. is it a map?

**Comment by Season000** [comment]
My picture suffix name is`. jpg`, sorry my English is not very good, I want to express the meaning is: Did the way i created the album in Google photo is wrong? I clicked on the "`album`", then "`new album`", and finally added a few photos.

**Comment by Season000** [comment]
The problem has been solved. Thank you！

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue. but I want to know how can you solve the issue. Can you share with us?
