### ISSUE TITLE
MMM-GooglePhotos and MMM-MMM-GroveGestures

### ISSUE THREAD

**Issue by skif78rus** [hermanho/MMM-GooglePhotos#20]
Hello eouia!
Sorry for my english. Can you please tell me how you can manage MMM-GooglePhotos with MMM-GroveGestures? I would like to realize flipping photos using gestures. Thanks for the help.

**Comment by eouia** [comment]
Sorry, GooglePhotos is not designed to navigate images. I'll consider in future, but the structure of modules needs to be changed entirely, so I cannot guarantee.

**Comment by skif78rus** [comment]
Thank you very much
