### ISSUE TITLE
Google Photos stop working after two days

### ISSUE THREAD

**Issue by karanbale** [hermanho/MMM-GooglePhotos#25]
I have been experiencing this issue for about a little over a month now, my google photos stop displaying photos after about every two days, and I have to restart the pi for it to start again. Is anyone else seeing this?
Is there any logs i can refer to on the pi to figure out what is going on?

**Comment by eouia** [comment]
I'll inspect this, but atm I couldn't find any suspicious thing. Because this module doesn't download image itself, so I don't think it's storage issue. Anyway I'll research more.

**Comment by karanbale** [comment]
Thank you. are there any logs or anything that I can look at to see whats going on? One strange thing I do notice is, I have installed MMM-Network module, that shows signal strength, and that also keeps indicating it has lost internet connection, however that is not true, because all of my other devices around the home seems to work just fine.

**Comment by eouia** [comment]
Well, some `[GPHOTO] blahblah...` would be logged in your log. But I think it's not so useful if you have that kind of problem.
For network issue, hmmm... I have no idea. Sorry.

**Comment by eouia** [comment]
Anyway, I'll update(or whole-new-build) this module in a few weeks.(I hope I have enough time to do) At that time I can inspect more deeply.

**Comment by eouia** [comment]
Have you still got the issue? I'll close this. Feel free to reopen the issue when you need.

**Comment by karanbale** [comment]
Yes I still have this issue. It has not been resolved yet. I am happy to provide any logs or debug this if you can point me in right directions. You said last time, you are going to update this module in few weeks, have you released it yet? Please re-open this issue.

**Comment by eouia** [comment]
- Tell me Your device (RPI 3B+?) os version (Raspbian Buster?), and node, npm (You can get it with `node -v` and `npm -v`)

- When your RPI was halted, is there any other symptom? (e.g; abnormal heating or some beeping or... any other things)

- How many pictures in your target google photo folders?
- Can you test with more smaller folder? e.g) under 100 photos. 

- Which modules are you using together?
- Check it happens again When you remove or comment out all other modules except MMM-GooglePhotos.

**Comment by karanbale** [comment]
I will get back to you by the end of the day PST. Thanks !

**Comment by karanbale** [comment]
My apologies, it totally slipped my mind. I will get most of the answers this evening and do some testing as you've requested.

**Comment by karanbale** [comment]
Device: Raspberry Pi 3B+
OS: Raspbian GNU/Linux Version 9
NPM: 6.4.1
Node: 10.15.3
When Pi was halted I noticed my wifi icon on the top chart of the mirror (using MMM-network-signal keeps searching for internet, but my internet works just fine).
I have 45 pictures in my google photo folder.
I have following modules installed:
- MMM-network-signal
- MMM-GooglePhotos
- alert
- updatenotification
- clock
- currentwether
- MMM-forecast-io
- calendar
- compliments
- newsfeed

Currently launched with just following modules, lets see if it reoccurs. (WW33.4 8:30PM)
- alert
- updatenotificationn
- clock
- MMM-GooglePhotos

**Comment by eouia** [comment]
Hmmm. there seems nothing suspicious specially. Weird.

**Comment by eouia** [comment]
Tomorrow I'll make one for you.

**Comment by eouia** [comment]
I've made a branch `forDebug` to leave somehow more logs. You can use that debug version.
```
git pull
git checkout forDebug
```

**Comment by eouia** [comment]
Basically `~/.pm2/logs/XXXX.log` would be. (But not sure)
ref. this; http://pm2.keymetrics.io/docs/usage/log-management/

**Comment by eouia** [comment]
See https://github.com/MichMich/MagicMirror/wiki/configuring-the-raspberry-pi#disable-wifi-power-save

**Comment by karanbale** [comment]
My power_save seems to be configured correctly as you can see below.
[
<img width="336" alt="Screen Shot 2019-09-03 at 8 14 09 AM" src="https://user-images.githubusercontent.com/17437391/64186001-f5d38200-ce22-11e9-8bfc-f3b66c572010.png">
](url)

**Comment by eouia** [comment]
So, now the issue happens again?

**Comment by karanbale** [comment]
There must be something else going on here. I am still losing network connection. anyways, I will pull the logs later today and attach them here for your reference so we can ensure this is network related issue and close it off then. I appreciate your help.
