### ISSUE TITLE
MMM-GooglePhotos Not showing images.

### ISSUE THREAD

**Issue by aunrea** [hermanho/MMM-GooglePhotos#27]
I have installed MMM-GooglePhotos. I did npm install. I ran the authentication script and got my album code. I don’t get any error messages, I just don’t have any images loading. The album has several images in it.

**Comment by eouia** [comment]
First you need to confirm these;

- Is it the same account of both your Google Photos service and the authed of project?
- The photos In the album are your owns? or shared from others?
- Did you tried other account or other albums? All the same bug?
- Show me the running-log (You can get it from log of pm2 or directly in the terminal shell with `npm start` instead pm2). I recommend you drop all other modules from config except only MMM-GooglePhotos to simplify log.
- Show me the config.

**Comment by aunrea** [comment]
> * Is it the same account of both your Google Photos service and the authed of project?

Yes

> * The photos In the album are your owns? or shared from others?

They are my own.

> * Did you tried other account or other albums? All the same bug?

Yes and yes.

> * Show me the running-log (You can get it from log of pm2 or directly in the terminal shell with `npm start` instead pm2). I recommend you drop all other modules from config except only MMM-GooglePhotos to simplify log.

I ran npm start and this is what the log said:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@6.11.3
> 3 info using node@v10.16.3
> 4 verbose stack Error: missing script: start
> 4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
> 4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:435:5
> 4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
> 4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:433:3)
> 4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:281:12
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
> 5 verbose cwd /home/pi/MagicMirror/modules/MMM-GooglePhotos
> 6 verbose Linux 4.19.66-v7+
> 7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
> 8 verbose node v10.16.3
> 9 verbose npm  v6.11.3
> 10 error missing script: start
> 11 verbose exit [ 1, true ]


> * Show me the config.

This is the config:

> {
> 			module: "MMM-GooglePhotos",
> 			position: "fullscreen_below",
> 			config: {
> 				albumId: "AF1QipN9tT1bBx0NxBvDA5eWVmWcKVnKhvkvOPFFTQjz",
> 				refreshInterval: 1000 * 60,
> 				scanInterval: 1000 * 60 * 10,
> 				sort: "time",
> 				showWidth: "100%",
> 				showHeight: "100%",
> 				originalWidthPx: 600,
> 				originalHeightPx: 800,
> 				mode: "hybrid",
> 			}
> 		},

**Comment by eouia** [comment]
you did wrong execution with 'npm start dev'. do it in MagicMirror directory.

**Comment by aunrea** [comment]
All that did was open the developers' panel. There are no errors there.

**Comment by eouia** [comment]
How about serverside log? you can get it on shell terminal directly when you execute `npm start dev`. You can change the focus of window by `Ctrl(or Alt) + Tab` after running MM.

Until now, I cannot find any special suspicious point at all. Anyway I need serverside log to inspect what happens on running.

**Comment by aunrea** [comment]
```
pi@raspberrypi:~/MagicMirror $ npm start dev

magicmirror@2.8.0 start /home/pi/MagicMirror
sh run-start.sh "dev"

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-TelegramBot
Initializing new module helper ...
Module helper loaded: MMM-ModuleScheduler
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
No helper found for module: MMM-pages.
Initializing new module helper ...
Module helper loaded: MMM-GooglePhotos
Initializing new module helper ...
Module helper loaded: MMM-BackgroundSlideshow
No helper found for module: clock.
No helper found for module: MMM-CountDown.
Initializing new module helper ...
Module helper loaded: MMM-MyCommute
Initializing new module helper ...
Module helper loaded: MMM-DarkSkyForecast
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: MMM-CalendarExt2
Initializing new module helper ...
Module helper loaded: MMM-Tools
Initializing new module helper ...
Module helper loaded: MMM-NetworkConnection
Initializing new module helper ...
Module helper loaded: MMM-network-signal
Initializing new module helper ...
Module helper loaded: MMM-PIR
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-TelegramBot
Connecting socket for: MMM-ModuleScheduler
Starting node helper for: MMM-ModuleScheduler
Connecting socket for: MMM-NotificationTrigger
Connecting socket for: MMM-GooglePhotos
MMM-GooglePhotos started
Connecting socket for: MMM-BackgroundSlideshow
Connecting socket for: MMM-MyCommute
====================== Starting node_helper for module [MMM-MyCommute]
Connecting socket for: MMM-DarkSkyForecast
====================== Starting node_helper for module [MMM-DarkSkyForecast]
Connecting socket for: MMM-CalendarExt2
Connecting socket for: MMM-Tools
Connecting socket for: MMM-NetworkConnection
MMM-NetworkConnection helper started ...
Connecting socket for: MMM-network-signal
MMM-network-signal helper started ...
Connecting socket for: MMM-PIR
Starting module helper: MMM-PIR
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1492:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:755:11)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
```

**Comment by eouia** [comment]
sorry, you didn't stop your previous MM instance. I think you are probably using 'pm2'. stop pm2 first then try again.

**Comment by aunrea** [comment]
```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.8.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-GooglePhotos
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-GooglePhotos
MMM-GooglePhotos started
Sockets connected & modules started ...
Launching application.
MMM-GooglePhotos initialized after loading.
[GPHOTO] Scan finished : 0
There is no scanned photo currently.
```

**Comment by eouia** [comment]
Log says you have no photo to scan in the album.

**Comment by aunrea** [comment]
I have photos in the album. I don't know why it's saying there is no photos.

**Comment by eouia** [comment]
Sorry, I have no idea. Three is no suspicious point in the source. Some ppl had reported same issue but those were their fault on creating or managing album.

https://github.com/eouia/MMM-GooglePhotos/issues/19

**Comment by aunrea** [comment]
I decided to uninstall and reinstall. How do you get the album lists after doing auth_and_test.js?

**Comment by eouia** [comment]
When auth_and_test.js is executed, your album list will be displayed after
authentication.

**Comment by aunrea** [comment]
It gets to auth_and_test started and stops, doing nothing else.

**Comment by eouia** [comment]
Show me your screen. 
When you execute the auth_and_test.js It will open a browser and navigate to some URL (Google auth page) or show that URL to copy and paste it into your browser manually. 
It doesn't?
And How did you this before? in your first attempt?

**Comment by aunrea** [comment]
I do all that but after I put in the code it says 

> auth_and_test started

and then it does nothing else.

Here is a screenshot:[https://www.dropbox.com/s/801zoh830phrznn/806028370_355563.jpg?dl=0]( https://www.dropbox.com/s/801zoh830phrznn/806028370_355563.jpg?dl=0)

**Comment by eouia** [comment]
It's very weird.
Try this;
```
cd ~/MagicMirror/modules/MMM-GooglePhotos
git pull
git checkout forDebug
node auth_and_test.js
```
It will show some more detailed information. Then show me the screen again. (You can upload image or file directly when you post the issue)

**Comment by aunrea** [comment]
![photo_2019-09-17_16-55-22](https://user-images.githubusercontent.com/11430952/65078907-13006880-d96c-11e9-95f9-b32c1f7b7a70.jpg)

**Comment by eouia** [comment]
hmmm...
it seems you have no "album" really.

**Comment by eouia** [comment]
wait, aren't you using "album" in GooglePhotos? If photos are not managed, themed or filtered by album, there could be too many unwanted photos to display. You'd better manage photos with album.

**Comment by aunrea** [comment]
I am using albums. I checked. Then I decided to check my API and realized I forgot to enable the google photos library. Very stupid of me. I was then able to get the list in terminal and now it works. THANK YOU SO MUCH FOR YOUR HELP!
