### ISSUE TITLE
Google Auth Loop

### ISSUE THREAD

**Issue by Ricardo96MC** [hermanho/MMM-GooglePhotos#29]
I am getting stuck in a loop during the step where I select what google account I want to use. I get directed to a page saying that my app isn't verified (post sms verification also), I clicked advanced, see my app name, click it, and redirected back to the select account screen. 
I have tried:
Rebuilding Electron
Creating new keys(2 sets)
Using both keys as the credentials.json file
Use multiple browsers
Use different google accounts to try and access the API

**Comment by eouia** [comment]
try to delete cache of browser, or use another browser(copy auth url and paste it into another)
