### ISSUE TITLE
Unable to see photos

### ISSUE THREAD

**Issue by bberg115** [hermanho/MMM-GooglePhotos#3]
This is most likely a user error, and not a module issue.

I was able to follow the steps and get the auth, but no photos. I'm worried it may be the node.js issue you mentioned, but I am unable to determine if this is the case due to my lack of experience.

Is there any way to see where the break/failure is happening? I do not see any warnings or errors on my MM.

**Comment by eouia** [comment]
If you could run MM without error, it would be not the case of node.js version issue.
Is there any error log? But some messages have to be shown. like 
`[GPHOTO] Scan finished :xx` or
`There is no scanned photo currently.`
or any other things.

**Comment by eouia** [comment]
Have you still been getting problems? I'll close this. Whenever you can ask more.

**Comment by bberg115** [comment]
Sorry for not responding earlier.

Unsure how it resolved itself... 

The next time I came home it was working. Maybe it was on Google's side? 

Thanks.
