### ISSUE TITLE
(node:1715) UnhandledPromiseRejectionWarning: Error: unauthorized_client

### ISSUE THREAD

**Issue by skif78rus** [hermanho/MMM-GooglePhotos#30]
![error](https://user-images.githubusercontent.com/49120458/65386797-b248a580-dd48-11e9-826c-0ff0c1dcb1a7.jpg)
Hello! Please tell me what could be the problem, I did everything according to the instructions
When starting node auth_and_test.js, the result is like this. What could be the problem?
(node:1715) UnhandledPromiseRejectionWarning: Error: unauthorized_client

**Comment by eouia** [comment]
However you seemed missing something on getting auth step( https://github.com/eouia/MMM-GooglePhotos#get-auth-and-albumid). can you show me your `credentials.json`? (eouia0819@gmail.com)

**Comment by skif78rus** [comment]
Sure!

**Comment by eouia** [comment]
I think you probably have `token.json` in your directory already but wrong. First, remove it then try again. With your `credentials.json`, I can success to make auth. (Your project name is `Wsf.kr` right?)

**Comment by skif78rus** [comment]
No, name loft001

**Comment by skif78rus** [comment]
Thank you so much!  I deleted the token.json file in the MMM-GooglePhotos folder and everything worked right away!
