### ISSUE TITLE
Keeps requesting authentication

### ISSUE THREAD

**Issue by aunrea** [hermanho/MMM-GooglePhotos#31]
Today the modules keep trying to authenticate. It's overwhelming my raspberry pi and the magic mirror. All the tabs in the image are the same page getting requested again.
![photo_2019-09-23_11-37-31](https://user-images.githubusercontent.com/11430952/65441384-50477900-ddf8-11e9-92ef-a633b2ec205f.png)

**Comment by aunrea** [comment]
I have removed MMM-GooglePhotos from the config but it keeps doing this. I have to keep my mirror off or else it overloads the system.

**Comment by aunrea** [comment]
After uninstalling it stopped happening.

**Comment by mnewhart** [comment]
I am setting up a MM and added your Google Photos following the install instructions. Nowhere does the instructions say to save the Authorize Token to the/a token.json file. If the npm auth_and_test is supposed to do this after pasting the auth permission code, it is not doing it. I get the list of albums with the codes in the terminal window and then it just sits there. It does not terminate automatically. I had to ctrl+x out of it. I have the credentials.json file in the folder but no token.json. This is what is causing the issue above (mine is doing the same thing). I can add the file but what should the key/name be for the value (copied token) be? I am looking in your auth.js and it is supposed to write a file but it doesn't. This may be a write permissions issue on Rasp PI 4 fresh install? not sure. If you can figure it out let me/us know.

**Comment by eouia** [comment]
@mnewhart 
`token.js` should be automatically created and saved.(and updated in your execution), so if `token.js` was not created, you cannot use this module. I cannot figure out why it was not created, but suggest to re-install or re-auth again.

**Comment by mnewhart** [comment]
I figured it out today. I did an ls -li and noticed that the folder and files had root:root perms not pi:pi. I did a chown -R on in the modules directory on your MMM-GooglePhotos folder and re-ran the auth_and_test.js and it works fine. I am not sure if git clone brought your project down as root. I added another MMM module today and their git cloned as pi:pi.

**Comment by mnewhart** [comment]
Also, the node auth_and_test.js does not terminate automatically. I had to ctrl+c out of it. You may want to add to copy the keys to albums and paste them into a text file in case they want to add them later.

**Comment by eouia** [comment]
@mnewhart 
1. If you had used `sudo git clone ...` it will have root permission.
2. auth_and_test.js is not terminated automatically. Sorry, I think it was just a one-time task, so I haven't given a care. so I didn't make exceptional process. Sorry again for the inconvenience.
