### ISSUE TITLE
File type and size restriction

### ISSUE THREAD

**Issue by nagaculun** [hermanho/MMM-GooglePhotos#35]
Hi,

Once in couple days, the magicmirror will freeze. I read in the forum, this might due to the photo is too big to handle. Requesting to restrict the file type to just pictures and limit the file size to XX mb.

Thanks

**Comment by eouia** [comment]
Well, I can't agree on that point. Because this module downloads only one picture at once temporarily. So I don't think it could make Memory problems on RPI. 
Anyway I'll inspect this issue more. And I have a plan to rebuild this module wholely from scratch but have not enough time nowadays.
