### ISSUE TITLE
Race condition when specifying multiple albums

### ISSUE THREAD

**Issue by philcali** [hermanho/MMM-GooglePhotos#36]
I've run into a race condition when specifying multiple albums. I traced to the following areas:

- Album pagination begins in a loop of album ID's: https://github.com/eouia/MMM-GooglePhotos/blob/master/node_helper.js#L70
- When the first pagination finishes, the clean up process begins: https://github.com/eouia/MMM-GooglePhotos/blob/master/node_helper.js#L117
- The cleanup cuts the temp items to "real" items: https://github.com/eouia/MMM-GooglePhotos/blob/master/node_helper.js#L149-L154
- Given the async nature of JS, "the last write, wins" so to speak, in this case the last album to finish paging will be the only one in the items array.

Once a get some spare cycles I can try to fix and cut a PR.

**Comment by eouia** [comment]
Frankly said multiple-albums supporting was not made by me. So I cannot assure its working. I believed that PR. When I was testing, it seemed working proper, so I accepted that PR.
Anyway, if you can provide a fix for us, it would be a great pleasure for us.

**Comment by philcali** [comment]
I totally understand. I realize now that the issue description was a little terse, but that was more or less notes for future me or some other person who might run into the same issue. To be clear: I think this module is great! I'm actively using it now 👍 

I should have a fix for this relatively soonish.

**Comment by philcali** [comment]
Fixed has been merged... Closing.
