### ISSUE TITLE
No image getting displayed

### ISSUE THREAD

**Issue by sushanttheone** [hermanho/MMM-GooglePhotos#4]
Hi,

First of all a big thank you for devloping this module. Its awesome and brings life to MagicMirror.

My issue is that I followed all the steps but no image is getting displayed/ Following is the output from the logs and the config file setting. Any help will be appreciated.

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
No helper found for module: MMM-GooglePhotos.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://calendar.google.com/calendar/ical/sushanttheone%40gmail.com/private-587993a3d8425423c5e3bdc4fde12d0b/basic.ics - Interval: 300000
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/UK-Holidays.ics - Interval: 300000
Create new calendar fetcher for url: http://www.facebook.com/ical/u.php?uid=100000426753977&key=AQAHcGDaafQeFW7I - Interval: 300000
Create new calendar fetcher for url: http://www.facebook.com/ical/b.php?uid=100000426753977&key=AQAHcGDaafQeFW7I - Interval: 300000
Create new news fetcher for url: https://timesofindia.indiatimes.com/rssfeedstopstories.cms - Interval: 300000
Create new news fetcher for url: http://feeds.feedburner.com/ndtvnews-top-stories - Interval: 300000
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed

{
  module: "MMM-GooglePhotos",
  position: "top_right",
  config: {
    albumId: "AGj1epWzJwv36L4KZ9sQB3ldrgG2z3BcotCDyCAZMlE0qgbFon13", // your album id from result of `auth_and_test.js`
    refreshInterval: 1000*60,  
    scanInterval: 1000*60*10, // too many scans might cause API quota limit also.
    //note(2018-07-29). It is some weird. API documents said temporal image url would live for 1 hour, but it might be broken shorter. So, per 10 min scanning could prevent dead url.

    sort: "time", //'time', 'reverse', 'random'
    showWidth: "800px", // how large the photo will be shown as. (e.g;'100%' for fullscreen)
    showHeight: "600px",
    originalWidthPx: 800, // original size of loaded image. (related with image quality)
    originalHeightPx: 600, // Bigger size gives you better quality, but can give you network burden.
    mode: "cover", // "cover" or "contain" (https://www.w3schools.com/cssref/css3_pr_background-size.asp)
  }
},

**Comment by sushanttheone** [comment]
Please close this. It was my mistake.

**Comment by eouia** [comment]
nice to you. I wish you good luck!
