### ISSUE TITLE
Not seeing photos

### ISSUE THREAD

**Issue by HI-IM-TIM** [hermanho/MMM-GooglePhotos#40]
I've setup my magic mirror on a raspberry pi zero w. I am able to auth_and_test.js with no issues. I've selected my album based on the album id but I am unable to see any photos. The album I've selected is my own album with my own photos. Any help would be greatly appreciated.

Thanks :)

Tim

**Comment by eouia** [comment]
Is there any error on log?

**Comment by eouia** [comment]
and This module is using higher version of nodeJS and npm. I suspect That RPI0 might have lower version of them.

**Comment by HI-IM-TIM** [comment]
No the system didn't present any errors. What are the correct versions of nodeJS and npm do I need?

**Comment by eouia** [comment]
If you got no error, don't care about the version.
The next thing to check is, `enabled your Google Photo Library API`.
![image](https://user-images.githubusercontent.com/1720610/70390427-30712b80-19cb-11ea-8075-5b26c55dc702.png)
https://console.developers.google.com/apis/library

**Comment by HI-IM-TIM** [comment]
Yup the Photos Library API is enabled.

**Comment by eouia** [comment]
Still, have the issue? Frankly, I have no idea more about it.
Anyway, send me your backend & frontend log both. (You can get both from `npm start dev`, frontend log in dev-console of MM screen and backend log in shell terminal)

**Comment by HI-IM-TIM** [comment]
finally got it working I had a bad install of node.js

thank you for your assistance. :)
