### ISSUE TITLE
Time Delay

### ISSUE THREAD

**Issue by firebug326** [hermanho/MMM-GooglePhotos#42]
Is there a way to configure the time each picture is shown? So far it seems to be random and I'm not very good with code to find a good way to delay such a thing. Any help would be greatly appreciated. Cheers.

**Comment by eouia** [comment]
It is not random. It depends on "refreshInterval", but due to loading and drawing image from network, there could be some time gap but not so big.
If you mean giving different time to each photos, it couldnt.
