### ISSUE TITLE
Using module while running MM in Docker?

### ISSUE THREAD

**Issue by simonsolberg** [hermanho/MMM-GooglePhotos#43]
Is it possible to use this module while running MagicMirror as a server in docker? 

If yes, please add this to the readme? :)

**Comment by eouia** [comment]
Sorry, I haven't tested that condition, so cannot tell you whether possible or not.

**Comment by simonsolberg** [comment]
@eouia ok so the following seems to be working: 

Step 1 in installation has to be done this way: 
`docker exec -it -w /opt/magic_mirror/modules/MMM-GooglePhotos magic_mirror npm install` 
This will execute the install command 

Auth_and_test.js can be run this way: 
`docker exec -it -w /opt/magic_mirror/modules/MMM-GooglePhotos magic_mirror node auth_and_test.js `
This will print a link that you will need to copy to a browser, after authenticating in the browser, copy the code back to the docker TTY, this will then print the album IDs. 

However I can't seem to get photos to show up on my magic mirror. 

If I check my https://console.developers.google.com/apis/dashboard site the album list request came through to Google API, but no other requests have come through.. 

Any ideas?

**Comment by eouia** [comment]
What log of MM says? It will leave some server-side log what this module try.

**Comment by eouia** [comment]
like this;
![image](https://user-images.githubusercontent.com/1720610/71277624-b0957a80-2355-11ea-8c70-c844df5cfd17.png)

**Comment by simonsolberg** [comment]
@eouia turns out i forgot a `,` after the last closing bracket of the config file.

So I got it working using docker. Would you like me to send a pull request updating the readme with instructions for docker?

**Comment by simonsolberg** [comment]
I don't know if this is the best way to do it, but I tried :) 
Updated README with Docker instructions in PR #45
