### ISSUE TITLE
creating the albums

### ISSUE THREAD

**Issue by kflick418** [hermanho/MMM-GooglePhotos#44]
I realize this may be a stupid question but I am very inexperienced. Where do I create the albums?

**Comment by eouia** [comment]
in `Google Photos`.  You should be a user of that service.
https://www.google.com/photos/about/

**Comment by kflick418** [comment]
I have an album created there. In your description it says that the album name should be along the lines of this here:

<ALBUM_NAME> : <ALBUM_ID>
travel to paris : AGj1epU5VMNoBGK9GDX3k_zDQaPT16Fe56o0N93eN6aXn-f21M98

Where is the "AGj1..." digits coming from? The last line of my install after I put the code in says auth_and_test started. Do I need to wait for that to run to get those digits?

**Comment by kflick418** [comment]
Is that supposed to be the code that i pasted?

**Comment by eouia** [comment]
What is shown on your terminal when you execute `auth_and_test.js` ?

**Comment by kflick418** [comment]
You'll have to excuse my inexperience, but how do I do that? This is my first project and all of this is new to me.

**Comment by kflick418** [comment]
I ran node auth_and_test.js and I got back the name of the album i have plus the long list of random digits. When i copied and pasted that into the module, nothing is coming up.

**Comment by eouia** [comment]
So is it something similar with this?
```
YOUR_ALBUM_NAME : BLAHBLAHBLAH...SOME ALPHANUMERIC CODES...
```
If so, done. do next step of installation.

**Comment by eouia** [comment]
If you just made the album, photos exist in that album?

**Comment by kflick418** [comment]
Ya, I created the album and moved a bunch of photos to it. On the config.js where it lists 
albumId: ["YOUR_GOOGLE_PHOTOS_ALBUM_ID","NEXT_GOOGLE_PHOTOS_ALBUM_ID"]

Should it look like 

albumId: ["YOUR_ALBUM_NAME : BLAHBLAHBLAH...SOME ALPHANUMERIC CODES"]

**Comment by eouia** [comment]
no, just 
```
albumId: ["AGj1epU5VMNo ... o0N93eN6aXn-f21M98"], // <- Yours
```

**Comment by kflick418** [comment]
I got it! Thank you so much for your help and patience, and for creating this module. I really appreciate it!
