### ISSUE TITLE
Pictures not displaying

### ISSUE THREAD

**Issue by JoshuaMekala** [hermanho/MMM-GooglePhotos#47]
Hi,
The pictures don't seem to be displaying on my screen. I double checked the album id, and I even messed around with the dimensions to no avail. I waited 2 minutes but nothing came up. Do I have to wait longer? Here is my code if you would like to check it.{
		  module: "MMM-GooglePhotos",
		  position: "top_right",
		  config: {
		    albumId: ["ABti5dbhErLiQmIyMOq6duWFJRFtO4je1FHzLKYG0uEOWV9qG6zh_35Mux_KvD_1xw28x2vrP], // your album id(s) from result of `auth_and_test.js`
		    refreshInterval: 1000 * 60,  
		    scanInterval: 1000 * 60*10, // too many scans might cause API quota limit also.
		    //note(2018-07-29). It is some weird. API documents said temporal image url would live for 1 hour, but it might be broken shorter. So, per 10 min scanning could prevent dead url.

		    sort: "time", //'time', 'reverse', 'random'
		    showWidth: "1500px", // how large the photo will be shown as. (e.g;'100%' for fullscreen)
		    showHeight: "800px",
		    originalWidthPx: 800, // original size of loaded image. (related with image quality)
		    originalHeightPx: 600, // Bigger size gives you better quality, but can give you network burden.
		    opacity: 1, // target "opacity" property (https://www.w3schools.com/cssref/css3_pr_opacity.asp)
		    mode: "hybrid", // "cover" or "contain" (https://www.w3schools.com/cssref/css3_pr_background-size.asp)
		    //ADDED. "hybrid" : if you set as "hybrid" it will change "cover" and "contain" automatically by aspect ratio.
		  }
		},

**Comment by eouia** [comment]
What your backend-log says?

**Comment by JoshuaMekala** [comment]
Hey, I solved it by putting the MMM-GooglePhotos in the modules folder. That solved my issue. I have another question however. When the images show up they go all the way to the left when I do a position of middle-center. It never goes to the center. Could you assist me with that please?

**Comment by eouia** [comment]
Which position did you put the module? The alignment will be inherited by a module position.

**Comment by JoshuaMekala** [comment]
I put it in Center_middle, but it went in the middle but it want to the left. It did not stay in the center of the screen.

**Comment by sherwood65633** [comment]
I'm not sure what I am doing wrong. I do not get an image. I have followed the instruction. all the google api auth went well. Any ideas?
	modules: [
				{
  module: "MMM-GooglePhotos",
  position: "center",
  config: {
    albumId: ["AIrw4TEWfjx1zigM8MWPP2eCFOcFXnt9x-f4TY67Dj9MepezDy3FNWFLGbNxxxxxxxxxuANyh"], // your album id(s) from result of `auth_and_test.js`
    refreshInterval: 1000*60,  
    scanInterval: 1000*60*10, // too many scans might cause API quota limit also.
    //note(2018-07-29). It is some weird. API documents said temporal image url would live for 1 hour, but it might be broken shorter. So, per 10 min scanning could prevent dead url.

    sort: "time", //'time', 'reverse', 'random'
    showWidth: "1920px", // how large the photo will be shown as. (e.g;'100%' for fullscreen)
    showHeight: "1080px",
    originalWidthPx: 1920, // original size of loaded image. (related with image quality)
    originalHeightPx: 1080, // Bigger size gives you better quality, but can give you network burden.
    opacity: 1, // target "opacity" property (https://www.w3schools.com/cssref/css3_pr_opacity.asp)
    mode: "hybrid", // "cover" or "contain" (https://www.w3schools.com/cssref/css3_pr_background-size.asp)
    //ADDED. "hybrid" : if you set as "hybrid" it will change "cover" and "contain" automatically by aspect ratio.
  }
},

**Comment by eouia** [comment]
@JamRaps 
Can you show me the screenshot of MagicMirror? I cannot figure out your current status.

@sherwood65633 
It's better to post a new issue. 
Anyway, show me your backend-log to diagnose what happened.

**Comment by sherwood65633** [comment]
http://prntscr.com/qpvm54
screen shot.
Which log would be best to send you? I Don't find a 'backend-log' file.
thank you so much for your help.
Mike

**Comment by JoshuaMekala** [comment]
hey @eouia I put the position to top_center so now it works my issue has been solved. @sherwood65633 I had the same issue as you. You have to move the MMM-GooglePhotos folder into your modules folder. Hope this helps!

**Comment by sherwood65633** [comment]
there is a 'nodes_modules' folder in the 'MMM-GooglePhotos' folder. Should
that folder be in the "MMM-GooglePhotos" tree or in the modules folder?
I'm still hot having any luck with this.

**Comment by JoshuaMekala** [comment]
You should go under the MagicMirror folder, then there is a folder that says modules. Put the whole MMM-GooglePhotos folder inside of it.

**Comment by sherwood65633** [comment]
that's what I have.
'/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules'
screen shot of the module.
http://prntscr.com/qpwbjx

**Comment by JoshuaMekala** [comment]
please show me your module folder under the MagicMirror folder.

**Comment by sherwood65633** [comment]
http://prntscr.com/qpwcrg

**Comment by JoshuaMekala** [comment]
weird idk what's going on then. Sorry I couldn't help

**Comment by sherwood65633** [comment]
I appreciate the effort. I might try to re-credential...?
thank you

**Comment by eouia** [comment]
@sherwood65633 
Ok, Let's examine. 

1) I think you've installed just MMM-GooglePhotos and MMM-Remote-Controller at this moment. backup your `config.js` then make new one which has only `MMM-GooglePhotos` and `clock` module inside it to make things simple.

2) Then, do this;
```sh
pm2 stop MagicMirror
cd ~/MagicMirror
npm start dev
```

It will show `dev-console` on your MM screen. You can get frontend-log on `console` tab. If there be suspicious errors, they will be displayed as red text.
And you can change the focus of window by press `Ctrl+Tab` (Or Alt+tab? I cannot remember...). You can return to terminal shell. In there backend-log would be displayed after execution of MM. 

Show or send me both logs to see what happened.
