### ISSUE TITLE
Still not producing images.

### ISSUE THREAD

**Issue by sherwood65633** [hermanho/MMM-GooglePhotos#50]
Thank you so much for the module. I am still having issues with the MMM-GooglePhotos mod. 
Still not producing images..
I find no syntax errors, but no images.
What log do you need to look at? and Where in the tree would I find it?
Thank you so much for your help with this.
Mike

**Comment by eouia** [comment]
To make things simple, remove or omit or comment out all other modules except `MMM-GooglePhotos` and `clock` module from `config.js`
Then stop `pm2` (if you are using), go to MagicMirror directory, then execute `npm start dev`. You can see `dev-console` on MM screen. In the `console` tab, you can get frontend log.
And if you return to terminal shell window (By pressing Ctrl+Tab maybe), you can get backend log in the terminal.

**Comment by sherwood65633** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'stop' ]
2 info using npm@6.13.6
3 info using node@v10.18.1
4 verbose stack Error: missing script: stop
4 verbose stack     at run
(/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at
/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at
/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_
(/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final
(/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then
(/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at
/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at
/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete]
(internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/pi/MagicMirror
6 verbose Linux 4.19.75-v7+
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "stop"
8 verbose node v10.18.1
9 verbose npm  v6.13.6
10 error missing script: stop
11 verbose exit [ 1, true ]

**Comment by sherwood65633** [comment]
http://prntscr.com/qqjgch
this is probably what you are looking to see?
thank you again for your help.
Mike

**Comment by sherwood65633** [comment]
http://prntscr.com/qqjgwb
this is right side of the console.
thank you so much.
Mike

**Comment by eouia** [comment]
Hmmm. how did you set `position` of module? Your error log says there would be some problem of `position`. Can you show me the configuration part about this module?

**Comment by sherwood65633** [comment]
{
module: "MMM-GooglePhotos",
position: "fullscreen_bottom",
config: {

albumId:
["AIrw4TEWfjx1zigM8MWPP2eCFOcFXnt9x-f4TY67Dj9MepezDy3FNWFLGbNMrFhoDrJPtZ8uANyh"],
refreshInterval: 1000*60,
scanInterval: 1000*60*10,


sort: "time",
showWidth: "1920px",
showHeight: "1080px",
originalWidthPx: 1920,
originalHeightPx:1080,
opacity: 1,
mode: "cover",

showDateLabel: true,
}

**Comment by eouia** [comment]
There is no `fullscreen_bottom` position. Use `fullscreen_below` or `bottom_bar` or any other proper position.

**Comment by sherwood65633** [comment]
I am running now. Thank you so much .
