### ISSUE TITLE
Photo Refresh ar 5 sec and 55 sec

### ISSUE THREAD

**Issue by kalbodave** [hermanho/MMM-GooglePhotos#51]
When starting up, the first photo will show for 5 sec and the next photo for 55 sec, and that will be the refresh cycle the rest of the time.  I have reinstalled complete system, MagicMirror2 & GooglePhotos from scratch 3 times.  When I CTRL+M out of MagicMirror, there are two instances of it runing in the top task bar . . . . . is that okay?  With MMM-GooglePhotos updating so often, and there not being very much (or very good) update instructions.  It seems as though I will have more opportunities to fix this.

My first installation of MagicMirror and GooglePhotos did not have this problem, but then there were updates to MagicMirror and GooglePhotos . . . .

**Comment by eouia** [comment]
Of course, double instances of MM could make an issue. Your every instance will try to refresh scanning, and it could make an irregular schedule of refreshing. I think you might have registered MagicMirror twice on your `pm2`.
