### ISSUE TITLE
node auth_and_test.js Error

### ISSUE THREAD

**Issue by kenderson** [hermanho/MMM-GooglePhotos#53]
Hi - I just installed MM2 and am working to get photos flowing through it. I seem to be hitting an error on the auth_and_test.js run. I've updated Node to the latest version - seemed to be what caused other folks problems in previous issues.

Any thoughts?

Thank You!

Terminal
```
XX@xxxxl:~/MagicMirror/modules/MMM-GooglePhotos $ node -v
v13.10.1
XX@xxxx:~/MagicMirror/modules/MMM-GooglePhotos $ node auth_and_test.js
/xxxxx/xxx/MagicMirror/modules/MMM-GooglePhotos/auth.js:32
  const oauthClient = new OAuth2Client(key.client_id, key.client_secret, key.redirect_uris[0]);
                      ^

TypeError: OAuth2Client is not a constructor
    at new Auth (/xxxxx/xxx/MagicMirror/modules/MMM-GooglePhotos/auth.js:32:23)
    at Object.<anonymous> (/xxxx/xxx/MagicMirror/modules/MMM-GooglePhotos/auth_and_test.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by eouia** [comment]
I think you’ve missed “npm install” on installation steps.

**Comment by kenderson** [comment]
Thanks for the quick response @eouia ! To make sure, I've reinstalled. See below. It looks like the same error occurred. Any other ideas?

```
xxx@xxx:~/MagicMirror/modules/MMM-GooglePhotos $ npm install
audited 295 packages in 7.176s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

xxx@xxx:~/MagicMirror/modules/MMM-GooglePhotos $ node auth_and_test.js
/home/pi/MagicMirror/modules/MMM-GooglePhotos/auth.js:32
  const oauthClient = new OAuth2Client(key.client_id, key.client_secret, key.redirect_uris[0]);
                      ^

TypeError: OAuth2Client is not a constructor
    at new Auth (/home/pi/MagicMirror/modules/MMM-GooglePhotos/auth.js:32:23)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/auth_and_test.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by eouia** [comment]
Very weird.
https://github.com/eouia/MMM-GooglePhotos/blob/4cf4beb671d8f8d37f0a13b30560f4ed8117d8e3/auth.js#L32
has nothing special suspicious point, 
https://github.com/eouia/MMM-GooglePhotos/blob/4cf4beb671d8f8d37f0a13b30560f4ed8117d8e3/auth.js#L12
if this code is executed.



Try this to check `google-auth-library` is installed?
```
cd ~/MagicMirror/modules/MMM-GooglePhotos
npm list | grep google-auth-library
```
It should show something similar to this;
```
├─┬ google-auth-library@1.6.1
```

**Comment by kenderson** [comment]
Hey @eouia - Confirmed. I see 1.6.1 installed. Any other thoughts? Should I try to remove and reinstall?

**Comment by eouia** [comment]
Totally weird. 

1. backup your `auth.js` (copy and rename it)
2. Open `auth.js` then modify.
- Go to line 17 (above `function Auth(config) {`)
https://github.com/eouia/MMM-GooglePhotos/blob/4cf4beb671d8f8d37f0a13b30560f4ed8117d8e3/auth.js#L16-L18
Then add this;
```js
console.log("###", OAuth2Client)
console.log("###", typeof OAuth2Client)
```
Then try again and Let's see what log will be written.

**Comment by kenderson** [comment]
@eouia - it returned undefined for both.

```
### undefined
### undefined
```

**Comment by eouia** [comment]
Really strange. 

In MMM-GooglePhotos directory, make this file and save it as `test.js` then try to execute `node test.js`
```
const {OAuth2Client} = require('google-auth-library');
console.log(OAuth2Client)
```

If not work (`undefined` again), Your system has something wrong, but I cannot figure out.

**Comment by eouia** [comment]
If possible, send me your auth.js and auth_and_test.js through mail. eouia0819@gmail.com

**Comment by eouia** [comment]
How about above `test.js` result?

**Comment by eouia** [comment]
??? How many lines your auth_and_test.js has now? line 168? is it right?

**Comment by kenderson** [comment]
Hey @eouia! I ran the test.js test and got the same "undefined" . The Auth_and_test.js looks to be 49 lines long.

That help? Should I try to reinstall?

**Comment by eouia** [comment]
I have no idea any more. Sorry, very weird and difficult to guess what happend. Maybe resinstall could be the solution but I'm not sure.

**Comment by kenderson** [comment]
Ok, I wiped it out and reinstalled it (a couple of times ;-) ). It required 'sudo npm install -g' to install with the right permissions on my side. It's likely to do with my set-up, but from what I read, that's a bullet-proof install method. Thank you again for all the help, @eouia !

**Comment by eouia** [comment]
Wait!!!

Are you using `sudo` for `npm install -g` ????? It will make total jam! Don't do it!
Usually `sudo` is no need at all (except some dependencies about `apt`) to install or use MagicMirror.
Rather it will make serious problems on MagicMirror.

Now I guess what was wrong. You might have installed MM or some modules with `sudo`,

Suggestion :
Format your SD, install Raspbian cleanly, adjust some environment for you.
Then Do install of MM and modules without `sudo` unless module instruction is saying forcely to do that.

**Comment by vuuhid** [comment]
Hello, I have the same error on MMM-AssistankMk2 Module when i do "node auth_and_test.js" what can I do? Coud you perhaps help with that please @eouia ?
