### ISSUE TITLE
OAuth-Client-ID Error

### ISSUE THREAD

**Issue by MrAirHD** [hermanho/MMM-GooglePhotos#59]
Google updated the developer API so there is no "others" when it comes to selecting wich type of the OAuth-Client-ID i want to create.
Which one should I select now ? I´ve tried a few but not a single one was working.

**Comment by eouia** [comment]
<img width="666" alt="1" src="https://user-images.githubusercontent.com/1720610/77527670-d9fdff00-6e8c-11ea-9e9f-59c7eabc6db9.png">
I think this would work. They might change name.

**Comment by MrAirHD** [comment]
Tanks man
