### ISSUE TITLE
How to make text more readable

### ISSUE THREAD

**Issue by johnnyswindle** [hermanho/MMM-GooglePhotos#6]
Installed your module and I love it.  The white text that is the default for all of the modules is a little hard to read.  What do you suggest to make text more readable?

Thanks...

**Comment by eouia** [comment]
Add this to your `css/custom.css`
```
.module {
  background-color:rgba(0,0,0,0.5)
}
```
You can add more CSS rules additionally.

**Comment by eouia** [comment]
Have you solved this problem? I'll close this issue. You can leave any further question.
I wish you have a good luck.
