### ISSUE TITLE
Error with node generate token

### ISSUE THREAD

**Issue by Alcor17** [hermanho/MMM-GooglePhotos#61]
Hi.
I'm noob with Magic Mirror and the eith MMM-GooglePhotos module. Now I'm trying to install this new version of MMM-GooglePhotos but when I execute the instruction at the terminal 
`node generate_token.js
`
Show the errors below:
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

The version of node (`node -v`) is 10.19.0

Thanks for your help in advance

**Comment by eouia** [comment]
Have you done `npm install` in modules directory?

**Comment by Alcor17** [comment]
Yes, I followed the instructions of installation

`git clone https://github.com/eouia/MMM-GooglePhotos.git
cd MMM-GooglePhotos
npm install`

**Comment by eouia** [comment]
Is there no error on installation? (npm install)
Anyway go to MMM-GooglePhotos then do `npm install --save open`.

**Comment by Alcor17** [comment]
Did it

> + open@6.4.0
added 2 packages from 1 contributor and audited 245 packages in 6.269s

> 2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

After I executed `npm fund` AND

> MMM-GooglePhotos@2.0.0
├─┬ glob@7.1.6
│ └── url: https://github.com/sponsors/isaacs
└─┬ p-limit@2.2.2
  └── url: https://github.com/sponsors/sindresorhus

**Comment by eouia** [comment]
How about your permission? Did you use `sudo` on installation of this module or MagicMirror?
test `ls -al` in MMM-GooglePhotos directory.

**Comment by Alcor17** [comment]
Thanks eouia, solved it with `sudo` as you said.

**Comment by eouia** [comment]
No. `sudo` is not the solution, rather being the reason of current and further messing.
Probably you've installed MM or some modules(incl. MMM-GooglePhotos) with `sudo`, And it will make whole system mess up.
Installation and usage of MM and modules don't need `sudo` at all unless instruction specially say it. 

My suggestion.
- Delete whole MM, and reinstall again and DO NOT USE `sudo` on installation. (except `sudo apt-get somethings`)

**Comment by Alcor17** [comment]
HEllo.

Not, only I installed MMM-GooglePhotos with `sudo` as you suggested. 

You mean that I deleted Magic  Mirror with modules included and again install it, right?

**Comment by eouia** [comment]
If you are sure only MMM-GooglePhotos by `sudo`, reinstalling that module is enough. But I'm worrying you have mistaken other modules or MM itself.

**Comment by Alcor17** [comment]
OK, I will reinstall all the MM modules again, but first I'll backup the config.js

**Comment by Alcor17** [comment]
Well, I uninstalled the modules and Magic Mirror, after I installed them again, but I have the same issue afresh. 
Not errors showed in the installation with `npm install` executed at MMM-GooglePhotos folder. 
I haven't used `sudo` instruction. 
Only I've installed other module and it works fine (MMM-Lunartic).

**Comment by eouia** [comment]
Sorry, Definitely it is permission issue. some modules might be abled to be installed and used even with whichever permission, but that is lucky case. Basically, without proper permission, your MM and my module will have possible further issue. And I can't help about that kind of things.

**Comment by eouia** [comment]
Check each directory (including MM itself) which permission have been set. All your MM directory should have permission as  owner `pi` user.

**Comment by Alcor17** [comment]
Finally I could create the generate_token.js but I don't know how. Now I'm trying show the module in my Magic Mirror with position "fullscreen_below", only it shows me the "Loading..." message.
Very grateful with your help.

**Comment by eouia** [comment]
set `debug:true`, and see the log what happened. How many photos are in your album? first scanning will take dozens seconds.

**Comment by Alcor17** [comment]
I got it! It was error mine. I changed the name of the folder to show, I wrote it with uppercase.
Thank you again.
Great job eouia!
