### ISSUE TITLE
Cover doesn't work as before

### ISSUE THREAD

**Issue by adi-miller** [hermanho/MMM-GooglePhotos#62]
It still keeps the side (or top / bottom) black stripes (or blurry when enabled). Am I doing something wrong?

**Comment by eouia** [comment]
show me your screenshot.

**Comment by eouia** [comment]
I think you address this.
https://github.com/eouia/MMM-GooglePhotos#tip

**Comment by adi-miller** [comment]
![image](https://user-images.githubusercontent.com/17914728/77797452-22324280-7082-11ea-8ccb-d6c4e6ff9ac3.png)

#GPHOTO_BACK {
	display:none;
}

#GPHOTO_CURRENT {
	background-size:cover;
}

**Comment by eouia** [comment]
Is that “fullscreen_below”?

**Comment by adi-miller** [comment]
Yes

**Comment by eouia** [comment]
Well, there is no reason not to work.
This is the result with
```
#GPHOTO_BACK {
display:none;
}

#GPHOTO_CURRENT {
background-size:cover;
}
```
![image](https://user-images.githubusercontent.com/1720610/77849571-fff90b80-71cc-11ea-9087-186e1630616e.png)

And this is the result `background-size:contain`.
![image](https://user-images.githubusercontent.com/1720610/77849600-46e70100-71cd-11ea-8948-afe88b209f20.png)


I can see one suspicious thing on your photo.
Why `photo info` has full screen width? Unless you have modified CSS, there could be some collisions with other modules.

To check this;
- Backup your `config/config.js` and `css/custom.css`
- Clearly create new config.js and css/custom.css. To make things simple, just put module `clock` and `MMM-GooglePhotos` then execute again. Let's see what happens.
