### ISSUE TITLE
No photo appears :( only loading...

### ISSUE THREAD

**Issue by ezar** [hermanho/MMM-GooglePhotos#63]
Hi @eouia !
Thanks for your magnific module, but I cannot make to work. I configure everything but only I can see: "Loading" @ screen.
Can you help me?
I activate debug but nothing relevant.

**Comment by ezar** [comment]
Seems that when I select an "generated" album fails :(

**Comment by eouia** [comment]
Set “debug:true” then see the log what happened.

**Comment by ezar** [comment]
I try it but no logs. Says 8191 photos but still loading. When remove calculated folder works again. Only 49 photos using this escenario

**Comment by eouia** [comment]
Show me the log

**Comment by ezar** [comment]
I reduce # of photos using config filters, but nothing ;(

```
1|MagicMirror  | [09:38:47.393] [LOG]    
1|MagicMirror  | [GPHOTOS] Getting album list
1|MagicMirror  | [09:38:47.493] [LOG]    
1|MagicMirror  | [GPHOTOS:AUTH] Token is alive.
1|MagicMirror  | [09:39:36.355] [LOG]    
1|MagicMirror  | [GPHOTOS:AUTH] Token is alive.
1|MagicMirror  | [09:39:59.589] [LOG]    
1|MagicMirror  | [GPHOTOS] Confirmed Uploadable album: MyMagicMirrorAlbum AN-tvRY_LfAtqB1s0KdNH3gQFPdsW3B2hr4TO9259gSjkdWvo6b89UuzIrn76w_HhhBtg4GfyB_D
1|MagicMirror  | [09:39:59.592] [LOG]    
1|MagicMirror  | [GPHOTOS] Finish Album scanning. Properly scanned : 1
1|MagicMirror  | [09:39:59.602] [LOG]    
1|MagicMirror  | [GPHOTOS] Initialized
1|MagicMirror  | [09:39:59.604] [LOG]    
1|MagicMirror  | [GPHOTOS] Start first scanning.
1|MagicMirror  | [09:39:59.606] [LOG]    [GPHOTOS] Start Album scanning
1|MagicMirror  | [09:39:59.616] [LOG]    
1|MagicMirror  | [GPHOTOS:AUTH] Token is alive.
1|MagicMirror  | [09:46:54.779] [LOG]    
1|MagicMirror  | [GPHOTOS] Getting 4511 photo(s) list from 'Magic Mirror'
1|MagicMirror  | [09:47:18.263] [LOG]    
1|MagicMirror  | [GPHOTOS] Total indexed photos: 4511
```

**Comment by eouia** [comment]
Hmmm, there seems no suspect log in your backend-logs.
How about front-end logs?
 - Some collisions between modules might prevent image loading

To check this;
1) To make things simple, remove all other modules from `config.js`, It can let us focus this symptom.
  - Back up `config.js` and make new one.
  - Remove all modules except `MMM-GooglePhotos` and `clock`. You can comment out, or set `disabled:true` for each modules.
2) Then, if you are using pm2, stop pm2 first. `pm2 stop all`
3) Go to MagicMirror directory, then do `npm start dev`
4) Now it will show dev-console on MM screen. you might see front-end log in `console` tab of that panel.

**Comment by swampy242001** [comment]
Hi Eouia,

First just like to say love the google photos, however I am following this, due to me having the same issue. This has only happened since the update. Thanks

**Comment by ezar** [comment]
No suspect log in frontend-logs.
I change my Google Photo folder to a "static" folder and it works. I add "calculated" photo folder to config.js and it fails :(

**Comment by eouia** [comment]
I don't understand what means `calculated`. I guess it could be some kind of  auto generated `smart photo list` by condition but cannot find what you address. Is it something like `For You` photo list?

**Comment by garcha** [comment]
hi @eouia, Thanks for putting this module together. I am also having blank screen issue. I'm seeing the following axios error:

`[15:29:13.867] [ERROR]  (node:1243) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

I'm grabbing the logs from pm2, is there a way to get better logs...

**Comment by eouia** [comment]
Hey guys. your issues are not the same and reason and solution will vary. I want you guys to keep the convention of the GitHub issue board.
- Post new issues per your own, not append your different issue to the other's original issue.


@garcha 
401 error means you have not proper authorization. It means you might have failed or got wrong token.json or credentials.. Read the instruction and retry again.

@swampy242001 So what? I'm not sure you have same issue or not. The symptom of "Image not displaying" would be the only one symptom, but could have a different reason. To know what happened, I need more detailed info.

And I'll not reply here any more except only to original issuer - ezar. Others have to post your owns.

**Comment by ezar** [comment]
Nothing! Seems an error ;(

**Comment by eouia** [comment]
@ezar So what kind of error. I have no clairvoyance. And what your meaning `calculated`. I can't understand it at all.

**Comment by eouia** [comment]
If possible, show me the picture, what you are mentioning as `calculated album`.

**Comment by eouia** [comment]
This is my Google Photo `Albums` page.  What you address `calculated`? Or where can I find it?
![image](https://user-images.githubusercontent.com/1720610/77944208-d5877b00-72be-11ea-9ea1-d673d9cba33d.png)

**Comment by ezar** [comment]
Create a new album using this option.

![0722FDD3-9120-4A39-BC41-A5D7BB60E3A5](https://user-images.githubusercontent.com/42736/77956498-41bfaa00-72d2-11ea-857e-dd8bb617164c.jpeg)

**Comment by eouia** [comment]
Well, now I understand what you mean. Content-Filter is not a genuine album, so it cannot be accessible by handling albums.
The dilemma is; To use the content filter and to use the album together is not possible. It needs a different approach with different API. 
So let me explain why I selected to use album instead content-filter.
Content-filter would gather all the pictures possible which Google thought proper. Most of the case, it is very useful and convenient. But sometimes improper pictures to be displayed on MM  would be also collected, So anyway manual managing will be needed. If so, album would be better to manage by manual.
Use a genuine album to show specific photos on MM.

**Comment by ezar** [comment]
Ok! Thanks @eouia

**Comment by nagaculun** [comment]
@eouia I have the same issue; loading only. Where can I grab the log ?
