### ISSUE TITLE
Module stops processing images if album request fails

### ISSUE THREAD

**Issue by olafnorge** [hermanho/MMM-GooglePhotos#64]
I recently encountered an issue if the request for albums fails, in my case, with an 503 error.

```
Mar 30 13:59:51 openhab photos[15694]: [13:59:51.990] [LOG]    [GPHOTOS:CORE] Error: Request failed with status code 503
Mar 30 13:59:51 openhab photos[15694]: [13:59:51.993] [ERROR]  (node:15694) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
Mar 30 13:59:51 openhab photos[15694]:     at createError (/home/openhab/photos/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
Mar 30 13:59:51 openhab photos[15694]:     at settle (/home/openhab/photos/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
Mar 30 13:59:51 openhab photos[15694]:     at IncomingMessage.handleStreamEnd (/home/openhab/photos/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11)
Mar 30 13:59:51 openhab photos[15694]:     at IncomingMessage.emit (events.js:323:22)
Mar 30 13:59:51 openhab photos[15694]:     at endReadableNT (_stream_readable.js:1204:12)
Mar 30 13:59:51 openhab photos[15694]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Mar 30 13:59:51 openhab photos[15694]: [13:59:51.994] [ERROR]  (node:15694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Mar 30 13:59:51 openhab photos[15694]: [13:59:51.994] [ERROR]  (node:15694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by eouia** [comment]
I think your photos are too many to handle. It might be caused by too often and many requests to get huge data. Maybe I can modify to add some time gap between requests, but until then, if possible, adjust your album size. You cannot display photos of over 8640 per day.

**Comment by eouia** [comment]
I'll fix it tomorrow.

**Comment by olafnorge** [comment]
I don't think they are too many as they are still below 1.000 and others do read much more from the API. It was just a missing try/catch. I added it in my PR.

**Comment by eouia** [comment]
503 error commonly happens when too often and many requests happen in short time. Just to catch error is not the real solution. I think.

**Comment by olafnorge** [comment]
Agree, the handling needs to be done in the catch but leaving the app in a unknown state is definitely wrong. The browser was not showing anything just a blank screen after it happened.

**Comment by olafnorge** [comment]
Btw, 503 means `Service Unavailable` not `429 Too Many Requests`. I assume the APIs of Google are implemented RESTful and are following the standards.

**Comment by eouia** [comment]
Ideally, 429 will be the right code. but really, some and many Google Things spit out 503 error for too often (rather than `too many`) requests. In most cases, adding some time gap is a tricky simple solution.

By the way, GP API is not so good to handle because of slow latency and small amount of result (max 50 items per query)

**Comment by olafnorge** [comment]
Ok, I'm sure you are right because you spend a tremendous amount of time in developing it. I would be more than happy if you find time solving it.

I'll keep my PR open in case you want to use it as a base. Just let me know if you want me to do so. If not I'll close it, no question. ;)

**Comment by eouia** [comment]
:)  I'll add just asleep() on your PR. Thanks for your contribution.
