### ISSUE TITLE
401 Error: disabled_client

### ISSUE THREAD

**Issue by caninjpn** [hermanho/MMM-GooglePhotos#7]
I followed the instructions to setup the module, but when I try to execute auth_and_test.js, the browser returns a 401.

it says that "This app is not yet configured to make OAuth requests..."

**Comment by eouia** [comment]
You might have missed something on setup project of google.

**Comment by eouia** [comment]
Have you still got problem? This is too old issue without feedback. So I'll close this. Merry holidays.
