### ISSUE TITLE
Can't show sharedAlbums

### ISSUE THREAD

**Issue by daskleinec** [hermanho/MMM-GooglePhotos#71]
Hello,
yesterday I update the module to the latest version. From this I can't show sharedAlbums. In latest version 1.x was this not a problem.

I tried to generate new "credentials.json" and "token.json". But this was not the solution.

I use latest version of MM 2.11.0

**Comment by eouia** [comment]
Weird, because, you cannot have accessed `sharedAlbums` in v1.x (That is why I made v2)
You means, `other's album`?

**Comment by daskleinec** [comment]
The albums that no longer work in V2.x are albums created by friends and shared with me. In V1.x I could use this kind of albums.

**Comment by eouia** [comment]
Open YOUR Google Photos web site, then  check where the album belongs to. ("Albums" or "Sharing")
<img width="1077" alt="111" src="https://user-images.githubusercontent.com/1720610/78564546-e3884f00-781c-11ea-804c-2b1ffffd78cf.png">

**Comment by daskleinec** [comment]
![GF-Albums](https://user-images.githubusercontent.com/63226837/78574339-2a307600-782a-11ea-88d3-928297d80680.JPG)

My albums are shared. I found the reason. In some albums are a blank character as last character. For example "Donnerstag in Augsburg " is the full name and not "Donnerstag in Augsburg". 

Thank you for your very fast support! Kind regards - Christian
