### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jcmarinn** [hermanho/MMM-GooglePhotos#72]
I'm getting this error with the module and not sure how to troubleshoot this, any help will be apreciated.

1|mm       | [2020-04-06 21:25:53.607] [ERROR]  (node:1112) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
1|mm       |     at createError (/home/jcmarin/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
1|mm       |     at settle (/home/jcmarin/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:18:12)
1|mm       |     at IncomingMessage.handleStreamEnd (/home/jcmarin/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:202:11)
1|mm       |     at IncomingMessage.emit (events.js:187:15)
1|mm       |     at endReadableNT (_stream_readable.js:1090:12)
1|mm       |     at process._tickCallback (internal/process/next_tick.js:63:19)
1|mm       | [2020-04-06 21:25:53.609] [ERROR]  (node:1112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
1|mm       | [2020-04-06 21:25:53.610] [ERROR]  (node:1112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eouia** [comment]
I need some more previous logs of your presentation.
Usually 503 errors happened on too many/ofren requests. How many do you have whole albums and photos in target albums?

**Comment by jcmarinn** [comment]
Yeah, it was a problem with the album, I have an automatic album (adds photos based on people) and it was growing to fast, it was still below the 8K but constantly growing.

I have set up with a static smaller album and is working now.

Quick question, I tried setting up with the "Favorites" album but it does not work, is there a way to point to the "Favorites" auto album?

**Comment by eouia** [comment]
Sorry, yours are not indeed album, rather than filter.
Unfortunately Google photos api doesn’t allow to use album and filter together. And i think album is more practical than filter for displaying photos on MM. auto filtered photos might not be proper to display. Auto-filtered photos would be often duplicated, not so best, similar, or mistakes. So I think album is better than filter. Sometimes manual management is better than auto-blind-generated set.
