### ISSUE TITLE
Refresh New photos 

### ISSUE THREAD

**Issue by jmigoliva** [hermanho/MMM-GooglePhotos#80]
Hello, is there a way to show imediatly New photos, the moment they are put in the álbum?
Right now i have to restart the mirror to see New photos.
Thanks

**Comment by ChrisAcrobat** [comment]
I don't know about immediately, but for me they appear, at least after a while, without a restart. Do you still have this problem?

**Comment by jmigoliva** [comment]
This week i noticed that the problema stop. As soon i move a photo it appears on the mirror. 
Thanks
