### ISSUE TITLE
Token does not refresh itself.

### ISSUE THREAD

**Issue by Blauenfeldt** [hermanho/MMM-GooglePhotos#86]
Whenever I turn on the raspberry pi, I manually have to go in and type "node generate_token.js", as it doesn't do by itself.
If I set the Debug to True, than the console will just say, that the token is expired.

**Comment by ChrisAcrobat** [comment]
I don't think it should, it should be a one time job.

**Comment by Blauenfeldt** [comment]
Sorry it didn't say it, but I got it working. Seems like i generated the first token with "Sudo node Generate.js" which made the token protected by root permissions.
