### ISSUE TITLE
can photo info show file name and date ?

### ISSUE THREAD

**Issue by iamihyunsu** [hermanho/MMM-GooglePhotos#87]
hello

Can photo info show file name and date ?

thank you.

안녕하세요~
올려주신거 잘이용중입니다~
혹시 GPHOTO_INFO에 사진이 만들어진 날짜와 filename를 출력할수있을까요?

**Comment by ChrisAcrobat** [comment]
Date: yes. See "timeFormat: "YYYY/MM/DD HH:mm" at https://github.com/ChrisAcrobat/MMM-GooglePhotos#usage.
File name: No, but I am planning to display the photos description if available. I have just been busy with other things.

**Comment by JalecoShowroom** [comment]
Is there a way to make the time stamp disapear i perfer a clean look but wasn't able to find where it is add ?

**Comment by ChrisAcrobat** [comment]
Yes, you can write som [custom CSS](https://github.com/ChrisAcrobat/MMM-GooglePhotos#tip).

**Comment by JalecoShowroom** [comment]
Can u show me how @ChrisAcrobat ?

**Comment by JalecoShowroom** [comment]
thx @ChrisAcrobat
