### ISSUE TITLE
Position / Padding

### ISSUE THREAD

**Issue by eccentricmeee** [hermanho/MMM-GooglePhotos#92]
Everything is working fine, thank you very much for this module! However, I have positioned this as top_center, it does show up but not on the top of the screen but dead in the middle, how can I modify this? I have played around with css file but cant get it to budge.

NVM, I changed the CSS in MMM-GooglePhotos. Again, thank you for this module!

**Comment by DavidD303** [comment]
@eccentricmeee what did you change in the CSS? i have mine set to top center and it keeps overlapping other modules trying to keep it in its third of the screen
