### ISSUE TITLE
Fix in Top Center

### ISSUE THREAD

**Issue by eccentricmeee** [hermanho/MMM-GooglePhotos#93]
Everything is working fine, thank you very much for this module! However, I have positioned this as top_center, it does show up and I have it on MMM-Carousel. Everytime it loads the Google Photos module the photo changes position and is not centered. It will go through the other modules again and randomly it is in the center again. How can I make it that it is always dead center?

**Comment by ChrisAcrobat** [comment]
How does your configuration look like? Are you able to record it on video?

**Comment by aneaville** [comment]
This has been open for over a year without response. I'm going to close the issue. If you would still like assistance, feel free to reopen.
