### ISSUE TITLE
Photo / Album changes won't update

### ISSUE THREAD

**Issue by forjer** [hermanho/MMM-GooglePhotos#94]
Hi,

As a noob to RPi and MagicMirror I could very well be overlooking something, but when I add another photo to my Google Photo album, shouldn't that automatically display on my MagicMirror?  Or do I have to add some more code to get this to work?

**Comment by howardginsburg** [comment]
I'm seeing the same thing and am wondering about it as well.  Appreciate any insights people can share.  Thanks!

**Comment by forjer** [comment]
If anyone has any input to this, please comment.  Thanks.

**Comment by ChrisAcrobat** [comment]
No, the module should be able to view the new photos without any trouble. Are you still having this issue? Do you have any `condition`s?

**Comment by forjer** [comment]
Yes, I am still having the issue. No conditions.

**Comment by aneaville** [comment]
How many photos do you have? Can you share your configuration?
It rescans the albums every 1 hour. How long have you let it run?

**Comment by forjer** [comment]
So I was apparently not understanding how it worked. Tried refresh interval, update interval and everything else I could think of except for patience. I didn't realize it was fixed at 60 minutes. Face-palm.

Thanks for the info. I set up a new Pi, installed MM and the Google Photos module, tested and it works as you said. Appreciate the replies.
